# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71eda17e0c7d8ead85dd3b4608a7b4aa6048e0c8502364913fe068bc4c7fff58d30af1613753d37623cdde8ad92fd534ff614f9bc53e81dcdb01e01267189c86

test:
  secret_key_base: ad3df2a55607e0de4d5646ac65822338889b4cccd9aab132008a1f0c8d97516ba3c0bde2aa8491f92eabeadc4316dafe711dd7747a70507daf7cc46d7324fee0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
